# Generated by Django 4.1.1 on 2022-09-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceWeightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requests_threshold', models.IntegerField(max_length=15)),
                ('price_coefficient', models.IntegerField(max_length=5)),
            ],
        ),
    ]
