# Generated by Django 4.1.1 on 2022-09-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThresholdWeightApp', '0002_thresholdweightmodel_delete_priceweightmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thresholdweightmodel',
            name='price_coefficient',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='thresholdweightmodel',
            name='requests_threshold',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
